site_name: Engin
site_description: A lightweight application framework for modern Python.
site_url: !ENV READTHEDOCS_CANONICAL_URL

theme:
    name: 'material'
    custom_dir: 'overrides'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

repo_name: invokermain/engin
repo_url: https://github.com/invokermain/engin/
edit_uri: ""

extra_javascript:
  - js/readthedocs.js

plugins:
- mkdocstrings
